import type { Metadata } from "next";
import Link from "next/link";
import { redirect } from "next/navigation";

import { MilestoneTimeline } from "@/components/MilestoneTimeline";
import { ProjectHealthCard } from "@/components/ProjectHealthCard";
import { RunAlertCycleButton } from "@/components/RunAlertCycleButton";
import { Badge } from "@/components/ui/badge";
import { buttonVariants } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { getAlerts, getProjects } from "@/lib/store";
import { cn } from "@/lib/utils";
import type { ProjectAlert } from "@/lib/types";
import { hasPaidAccess } from "@/lib/paywall";

export const metadata: Metadata = {
  title: "Dashboard",
  description:
    "Monitor project health, milestone risk, and deadline alerts across GitHub and Linear in one engineering command center."
};

const alertBadgeVariant: Record<ProjectAlert["severity"], "default" | "warning" | "danger"> = {
  info: "default",
  warning: "warning",
  critical: "danger"
};

export default async function DashboardPage() {
  const paid = await hasPaidAccess();

  if (!paid) {
    redirect("/pricing?locked=1");
  }

  const [projects, alerts] = await Promise.all([getProjects(), getAlerts(12)]);

  const activeProjects = projects.length;
  const atRiskCount = projects.filter((project) => project.status !== "on_track").length;
  const avgHealth =
    activeProjects > 0
      ? Math.round(
          projects.reduce((sum, project) => sum + project.healthScore, 0) /
            activeProjects
        )
      : 0;

  return (
    <main className="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8">
      <div className="mb-8 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h1 className="text-3xl font-bold">Project Health Dashboard</h1>
          <p className="mt-1 text-[#cbd5e1]">
            Real-time visibility for milestone confidence, blocker load, and looming deadlines.
          </p>
        </div>
        <div className="flex gap-3">
          <Link href="/onboarding" className={cn(buttonVariants({ variant: "secondary" }))}>
            Add integrations
          </Link>
          <RunAlertCycleButton />
        </div>
      </div>

      <section className="mb-6 grid gap-4 sm:grid-cols-3">
        <Card className="bg-[#0f172a]/70">
          <CardHeader>
            <CardDescription>Tracked projects</CardDescription>
            <CardTitle className="text-3xl">{activeProjects}</CardTitle>
          </CardHeader>
        </Card>
        <Card className="bg-[#0f172a]/70">
          <CardHeader>
            <CardDescription>At risk or off track</CardDescription>
            <CardTitle className="text-3xl">{atRiskCount}</CardTitle>
          </CardHeader>
        </Card>
        <Card className="bg-[#0f172a]/70">
          <CardHeader>
            <CardDescription>Average health score</CardDescription>
            <CardTitle className="text-3xl">{avgHealth}</CardTitle>
          </CardHeader>
        </Card>
      </section>

      <section className="mb-6 grid gap-4 lg:grid-cols-2">
        {projects.map((project) => (
          <ProjectHealthCard key={project.id} project={project} />
        ))}
      </section>

      <section className="mb-6 grid gap-4 lg:grid-cols-2">
        {projects.slice(0, 2).map((project) => (
          <MilestoneTimeline key={`${project.id}-timeline`} project={project} />
        ))}
      </section>

      <section className="grid gap-4 lg:grid-cols-2">
        <Card className="bg-[#0f172a]/70">
          <CardHeader>
            <CardTitle>Recent alerts</CardTitle>
            <CardDescription>Generated by deadline analysis and blocker severity checks.</CardDescription>
          </CardHeader>
          <CardContent className="space-y-2">
            {alerts.length === 0 ? (
              <p className="text-sm text-[#94a3b8]">No alerts yet. Run an analysis cycle to generate the first signal.</p>
            ) : (
              alerts.map((alert) => (
                <div key={alert.id} className="rounded-lg border border-[#1f2937] bg-[#0b1220] p-3 text-sm">
                  <div className="mb-1 flex items-center justify-between gap-2">
                    <Badge variant={alertBadgeVariant[alert.severity]}>{alert.severity}</Badge>
                    <span className="text-xs text-[#64748b]">{new Date(alert.createdAt).toLocaleString()}</span>
                  </div>
                  <p className="text-[#dbeafe]">{alert.message}</p>
                </div>
              ))
            )}
          </CardContent>
        </Card>

        <Card className="bg-[#0f172a]/70">
          <CardHeader>
            <CardTitle>Execution guidance</CardTitle>
            <CardDescription>How high-performing teams use ProjectZeta9 day to day.</CardDescription>
          </CardHeader>
          <CardContent className="space-y-3 text-sm text-[#cbd5e1]">
            <p>1. Run analysis after every planning meeting and at each end-of-day handoff.</p>
            <p>2. Route critical alerts to the project owner within 30 minutes.</p>
            <p>3. Update milestone blockers in GitHub or Linear instead of editing status docs manually.</p>
            <p>4. Review the at-risk list weekly and reset scope before deadlines are jeopardized.</p>
          </CardContent>
        </Card>
      </section>
    </main>
  );
}
